name: infection

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  infection:
    name: "Running Infection"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, intl, fileinfo, sodium
          coverage: xdebug

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Run infection
        run: ./vendor/bin/infection --show-mutations --min-msi=100 --min-covered-msi=100
